validates_name: 50
validates_email: 255
validates_password: 6
size_avatar: 80
session_value: 1
record_page: 10
time_password_reset: 2
length_micro: 140
picture_size: 5
resize_to_limit: 400
size_gravatar: 30
